#!/usr/bin/env python3
"""Turn an image, GIF or frame folder into a DigiScreen overlay mod.

DigiScreen overlays a full-panel picture (or animation) over the live UI.
Press the device's combo to toggle it; press it again to remove it. Nothing
else changes and the machine keeps running underneath.

  Digitakt: TRK + YES      Digitone: MIDI + YES

Two hooks do the work (see ../docs/TECHNICAL.md):

  * `queue_send` entry -- UI key events are 16-byte records. The stub ignores
    repeats, latches the modifier on its press and toggles on the YES press
    that follows, then clears the latch. So YES alone never triggers and a
    missed release cannot stick.
  * `panel_diff` / `panel_flush` entry -- copies the current 1 KB frame into
    `fb_front` before the stock present; multi-frame inputs advance one frame
    per present.

Usage:
    python make_machine.py IMAGE|GIF|DIR --dn -o ../mods/NAME-dn [--name N]
    python make_machine.py IMAGE|GIF|DIR        -o ../mods/NAME-dt

Needs Python 3 with Pillow.
"""
import argparse
import glob
import json
import os
import re
import sys

W, H = 128, 64
FRAME = W * H // 8
MAX_FRAMES = 60

# Runtime key codes (measured -- NOT the firmware's panel-test table).
# Digitakt: TRK=2, YES=12.  Digitone: MIDI=2, YES=13.
# Flag bits: 0x01 press, 0x08 repeat, 0x10 release.
DT = dict(
    device='digitakt-mk1', os='1.53', combo='TRK+YES',
    uiq=0x4060FC28,
    qsend=0x40001B7A, qsend8=0x40001B82, stock_qsend='2f0a2f02206f000c',
    diff=0x400E60E2, diff8=0x400E60EA, stock_diff='4fefffd848d71c7c',
    flush=0x400E6064, flush8=0x400E606C, stock_flush='4fefffe448d7043c',
    fb=0x4020D8F8, mod=2, yes=12,
)
DN = dict(
    device='digitone-mk1', os='1.43', combo='MIDI+YES',
    uiq=0x4052A6BC,
    qsend=0x40001CDA, qsend8=0x40001CE2, stock_qsend='2f0a2f02206f000c',
    diff=0x400F8EFA, diff8=0x400F8F02, stock_diff='4fefffd848d71c7c',
    flush=0x400F8E7C, flush8=0x400F8E84, stock_flush='4fefffe448d7043c',
    fb=0x40241A44, mod=2, yes=13,
)

ASM = '''/* DigiScreen: press {combo} to overlay {src} ({n} frame(s)). Generated. */
        .section .run, "ax"

        .globl  digiscreen_key
        .globl  digiscreen_diff
        .globl  digiscreen_flush

/* queue_send(queue,item): latch {combo}, ignore repeats, toggle on YES. */
digiscreen_key:
        move.l  4(%a7),%d0
        cmpi.l  #0x{uiq:08x},%d0
        bne     9f
        movea.l 8(%a7),%a0
        tst.b   (%a0)
        bne     9f
        move.l  8(%a0),%d1
        btst    #3,%d1                  /* repeat? ignore */
        bne     9f
        move.l  4(%a0),%d0
        cmpi.l  #{yes},%d0
        beq     1f
        cmpi.l  #{mod},%d0
        bne     9f
1:      btst    #4,%d1                  /* release */
        bne     5f
        btst    #0,%d1                  /* press */
        beq     9f
        cmpi.l  #{yes},%d0
        bne     2f
        tst.l   mod_latch               /* YES press: consume the latch */
        beq     9f
        clr.l   mod_latch
        move.l  overlay,%d1
        not.l   %d1
        move.l  %d1,overlay
        bra     9f
2:      moveq   #1,%d1                  /* modifier press: latch it */
        move.l  %d1,mod_latch
        bra     9f
5:      clr.l   mod_latch               /* any release clears the latch */
9:      move.l  %a2,-(%a7)
        move.l  %d2,-(%a7)
        movea.l 0xc(%a7),%a0
        jmp     0x{qsend8:08x}

digiscreen_diff:
        bsr     digiscreen_draw
        lea.l   -0x28(%a7),%a7
        movem.l %d2-%d6/%a2-%a4,(%a7)
        jmp     0x{diff8:08x}

digiscreen_flush:
        bsr     digiscreen_draw
        lea.l   -0x1c(%a7),%a7
        movem.l %d2-%d5/%a2,(%a7)
        jmp     0x{flush8:08x}

digiscreen_draw:
        tst.l   overlay
        beq     9f
        movea.l 0x{fb:08x},%a0
        tst.l   %a0
        beq     9f
        move.l  frame_idx,%d1
        addq.l  #1,%d1
        cmpi.l  #{n},%d1
        bne     1f
        clr.l   %d1
1:      move.l  %d1,frame_idx
        lsl.l   #8,%d1
        lsl.l   #2,%d1
        add.l   #digiscreen_frames,%d1
        movea.l %d1,%a1
        move.l  #256,%d0
2:      move.l  (%a1)+,(%a0)+
        subq.l  #1,%d0
        bne     2b
9:      rts

        .balign 4
overlay:
        .long   0
mod_latch:
        .long   0
frame_idx:
        .long   0
        .balign 4
digiscreen_frames:
        .incbin "frames.bin"
'''

README = '''# {name}

Generated by `tools/make_machine.py` from `{src}` ({n} frame(s)) for
**{device} {os}**.

{combo} toggles a full-panel overlay of this image over the live UI; press it
again to remove it.

## Build and install

Needs `core` (`core` for Digitakt, `core-dn1` for Digitone) from elekloader and
the matching stock `.syx`.

```sh
cd elekloader
python -m elekloader.sdk.build <this dir> --stock <stock .syx>
python -m elekloader.patch --stock <stock .syx> \\
    --mod mods/{core}/out/{corever}.elemod \\
    --mod <this dir>/out/{mid}-1.0.elemod --out digiscreen.syx --version 2.0x
```
'''


def slug(s):
    return re.sub(r'[^a-z0-9]+', '-', s.lower()).strip('-') or 'art'


def load_frames(path):
    from PIL import Image, ImageSequence
    if os.path.isdir(path):
        fs = sorted(glob.glob(os.path.join(path, '*.png')))
        return [Image.open(f).copy() for f in fs]
    im = Image.open(path)
    if getattr(im, 'is_animated', False) and getattr(im, 'n_frames', 1) > 1:
        return [f.copy() for f in ImageSequence.Iterator(im)]
    return [im.copy()]


def decimate(frames, limit=MAX_FRAMES):
    if len(frames) <= limit:
        return frames
    step = len(frames) / limit
    return [frames[int(i * step)] for i in range(limit)]


def fit(img):
    from PIL import Image
    img = img.convert('L')
    # Exact integer downscales (pixel art) use nearest; anything else is scaled
    # to fit and centred, so a 4x source is reproduced pixel for pixel.
    if (img.width % W == 0 and img.height % H == 0
            and img.width // W == img.height // H):
        return img.resize((W, H), Image.NEAREST)
    scale = min(W / img.width, H / img.height)
    nw, nh = max(1, round(img.width * scale)), max(1, round(img.height * scale))
    img = img.resize((nw, nh), Image.LANCZOS)
    canvas = Image.new('L', (W, H), 0)
    canvas.paste(img, ((W - nw) // 2, (H - nh) // 2))
    return canvas


def pack(img, invert=False, dither=False):
    """A Pillow image -> 1024 bytes in the panel format.

    byte = page + 8*column, page = 7 - (y>>3), bit = y&7 (LSB first)."""
    img = fit(img)
    if invert:
        img = img.point(lambda v: 255 - v)
    one = img.convert('1') if dither else \
        img.point(lambda v: 255 if v > 127 else 0).convert('1')
    px = one.load()
    buf = bytearray(FRAME)
    for y in range(H):
        page, bit = 7 - (y >> 3), y & 7
        for x in range(W):
            if px[x, y]:
                buf[page + 8 * x] |= 1 << bit
    return bytes(buf)


def write_mod(outdir, name, src, dev, pack_kw=None):
    pack_kw = pack_kw or {}
    # A .bin input is already packed panel frames (1024 bytes each).
    if str(src).lower().endswith('.bin'):
        data = open(src, 'rb').read()
        packed = [data[i:i + FRAME] for i in range(0, len(data), FRAME)][:MAX_FRAMES]
    else:
        packed = [pack(f, **pack_kw) for f in decimate(load_frames(src))]
    n = len(packed)
    os.makedirs(outdir, exist_ok=True)
    open(os.path.join(outdir, 'frames.bin'), 'wb').write(b''.join(packed))
    asm = ASM.format(src=os.path.basename(src.rstrip('/\\')), combo=dev['combo'],
                     n=n, uiq=dev['uiq'], yes=dev['yes'], mod=dev['mod'],
                     qsend8=dev['qsend8'], diff8=dev['diff8'],
                     flush8=dev['flush8'], fb=dev['fb'])
    open(os.path.join(outdir, 'splash.s'), 'w').write(asm)
    mid = slug(name)
    mod = {
        'id': mid, 'version': '1.0', 'title': name, 'category': 'Display',
        'author': 'DigiScreen', 'license': 'GPL-2.0-or-later',
        'description': 'Press %s to overlay %s (%d frame%s) on the live UI; '
                       'press it again to remove it.'
                       % (dev['combo'], os.path.basename(src.rstrip('/\\')),
                          n, '' if n == 1 else 's'),
        'device': dev['device'], 'os': dev['os'],
        'sources': ['splash.s'],
        'sites': [
            {'addr': '0x%08x' % dev['qsend'], 'stock': dev['stock_qsend'],
             'op': 'jmp', 'target': 'digiscreen_key'},
            {'addr': '0x%08x' % dev['diff'], 'stock': dev['stock_diff'],
             'op': 'jmp', 'target': 'digiscreen_diff'},
            {'addr': '0x%08x' % dev['flush'], 'stock': dev['stock_flush'],
             'op': 'jmp', 'target': 'digiscreen_flush'},
        ],
        'requires': ['core'], 'resources': {'names': []},
    }
    open(os.path.join(outdir, 'mod.json'), 'w').write(
        json.dumps(mod, indent=1) + '\n')
    core = 'core' if dev['device'] == 'digitakt-mk1' else 'core-dn1'
    corever = 'core-2.1' if dev['device'] == 'digitakt-mk1' else 'core-dn1-2.0a'
    open(os.path.join(outdir, 'README.md'), 'w').write(
        README.format(name=name, src=os.path.basename(src.rstrip('/\\')),
                      n=n, mid=mid, device=dev['device'], os=dev['os'],
                      combo=dev['combo'], core=core, corever=corever))
    return mid, n


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('image', help='a PNG, a GIF, or a folder of PNG frames')
    ap.add_argument('-o', '--out', required=True)
    ap.add_argument('--dn', action='store_true', help='Digitone instead of Digitakt')
    ap.add_argument('--name', help='mod name/title (default from the file)')
    ap.add_argument('--dither', action='store_true')
    ap.add_argument('--invert', action='store_true')
    a = ap.parse_args()
    dev = DN if a.dn else DT
    name = a.name or os.path.splitext(os.path.basename(a.image.rstrip('/\\')))[0]
    mid, n = write_mod(a.out, name, a.image, dev,
                       {'dither': a.dither, 'invert': a.invert})
    print('wrote %s  (%s, %d frame(s), %s %s)'
          % (a.out, mid, n, dev['device'], dev['os']))
    return 0


if __name__ == '__main__':
    sys.exit(main())
